//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOTvorchestvo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PynktVydachy
    {
        public string IDProduct { get; set; }
        public string CityDevilery { get; set; }
        public string YlicaDostavki { get; set; }
        public Nullable<int> KolichestvoTovara { get; set; }
    }
}
